# Generated by Django 5.1 on 2024-09-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancyapp', '0003_alter_patient_db_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
