# Generated by Django 5.1 on 2024-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancyapp', '0005_save_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buk'),
        ),
    ]
