# Generated by Django 5.1 on 2024-09-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancyapp', '0006_save_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save_book',
        ),
    ]
