# Generated by Django 5.1 on 2024-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancyapp', '0009_proceed_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True)),
                ('baby_development', models.TextField()),
                ('mother_symptoms', models.TextField()),
                ('tips', models.TextField()),
            ],
        ),
    ]
