# Generated by Django 5.1 on 2024-09-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancyapp', '0010_pregnancyweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PregnancyWeek',
        ),
    ]
