# Generated by Django 5.1 on 2024-09-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.TextField(blank=True, max_length=500, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
