# Generated by Django 5.1 on 2024-09-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_menu_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_db',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='menu_db',
            name='image3',
        ),
    ]
