# Generated by Django 5.1 on 2024-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_menu_db_image2_remove_menu_db_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_db',
            name='price',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
