# Generated by Django 5.1 on 2024-09-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_menu_db_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_db',
            name='benefit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
