# Generated by Django 5.1 on 2024-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_menu_db_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books')),
            ],
        ),
        migrations.AlterField(
            model_name='menu_db',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
