# Generated by Django 5.1 on 2024-09-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_image1_menu_db_pro_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_db',
            old_name='pro_image1',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='menu_db',
            name='pro_image2',
        ),
        migrations.RemoveField(
            model_name='menu_db',
            name='pro_image3',
        ),
        migrations.AddField(
            model_name='menu_db',
            name='benefit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu_db',
            name='ingredients',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
