# Generated by Django 5.1 on 2024-09-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_pro_image1_menu_db_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_db',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='menu_db',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
