# Generated by Django 5.1 on 2024-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_menu_db_image2_menu_db_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu_db',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='menu_db',
            name='image3',
        ),
    ]
