# Generated by Django 5.1 on 2024-09-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_book_db_image2_book_db_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_db',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='book_db',
            name='image3',
        ),
    ]
